id: opecha:P006855
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4254
  title: སྐྱབས་འགྲོའི་རྣམ་བཤད་ལམ་བཟང་གསལ་བའི་ཉི་མ་སྡོམ་གསུམ་བདུད་རྩིའི་ཆུ་གཏེར་གཞན་སྟོང་བགྲོ་གླེང་ཐེངས་གཉིས་པའི་དྲིས་ལན་དཔག་བསམ་ལྗོན་ཤིང
  volume: ''
  author: ''
