id: P006855
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG4254
  title: སྐྱབས་འགྲོའི་རྣམ་བཤད་ལམ་བཟང་གསལ་བའི་ཉི་མ་སྡོམ་གསུམ་བདུད་རྩིའི་ཆུ་གཏེར་གཞན་སྟོང་བགྲོ་གླེང་ཐེངས་གཉིས་པའི་དྲིས་ལན་དཔག་བསམ་ལྗོན་ཤིང
  author: ''
  volumes:
    20e328091f104d25b51b3af6f98ff302:
      image_group_id: I1KG4977
      title: ''
      volume_number: 1
      total_pages: 308
      base_file: v001.txt
